# Generated by Django 6.0.2 on 2026-03-07 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_add_user_to_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_read', 'Plan to Read')], max_length=20)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('current_chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('is_masterpiece', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='userbooks_u_user_id_6a8159_idx'), models.Index(fields=['book'], name='userbooks_u_book_id_a17e2d_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
