# Generated by Django 6.0.2 on 2026-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='reread_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
