# Generated by Django 6.0.2 on 2026-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used', 'created_at'], name='users_passw_user_id_c8c4b0_idx'),
        ),
    ]
