# Generated by Django 6.0.2 on 2026-03-23 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken_users_passw_user_id_c8c4b0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_coefficient',
            field=models.FloatField(blank=True, default=0.0, help_text='The user-specific reading speed coefficient (relative to an ideal reader).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
