# Generated by Django 6.0.2 on 2026-03-05 19:33

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', validators=[apps.common.validators.validate_cover_image])),
                ('description', models.TextField(max_length=5000)),
                ('book_type', models.CharField(choices=[('book', 'Book'), ('comic', 'Comic')], default='book', max_length=20)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('pages_total', models.PositiveIntegerField(blank=True, null=True)),
                ('chapters_total', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('parent_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='books.book')),
                ('tags', models.ManyToManyField(related_name='books', to='books.tag')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title'], name='book_title_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['title_en'], name='book_title_en_trgm', opclasses=['gin_trgm_ops']), models.Index(fields=['book_type'], name='books_book_book_ty_496255_idx'), models.Index(fields=['country'], name='books_book_country_9fbee2_idx')],
            },
        ),
    ]
