# Generated by Django 6.0.2 on 2026-03-14 15:53

import django.db.models.deletion
from django.db import migrations, models


def copy_tag_names_to_translations(apps, schema_editor) -> None:  # noqa: ARG001
    """Copy legacy Tag.name into ru/en/de translations before field removal."""
    tag_model = apps.get_model('books', 'Tag')
    translation_model = apps.get_model('books', 'TagTranslation')
    language_codes = ('ru', 'en', 'de')

    for tag in tag_model.objects.all().iterator():
        for language_code in language_codes:
            translation_model.objects.get_or_create(
                master_id=tag.pk,
                language_code=language_code,
                defaults={'name': tag.name},
            )


def noop_reverse(apps, schema_editor) -> None:  # noqa: ARG001
    """No-op reverse migration placeholder for RunPython."""


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.tag')),
            ],
            options={
                'verbose_name': 'tag Translation',
                'db_table': 'books_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(copy_tag_names_to_translations, noop_reverse),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
