# Generated by Django 6.0.2 on 2026-03-15 12:02

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_tag_name_tagtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.tag'),
        ),
    ]
