"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()
environ.Env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost'])  # pyright: ignore[reportArgumentType]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'apps.users',
    'apps.books',
    'apps.userbooks',
    'apps.reviews',
    'apps.common',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'parler',
    'parler_rest',
    'django_celery_beat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'apps.common.middleware.AdminIPRestrictionMiddleware',  # place it after authentication middleware
]

# Cache

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

BOOKS_CACHE_TTL = 60 * 5  # Cache books list for 5 minutes
SEARCH_CACHE_TTL = 60 * 3  # Cache search results for 3 minutes
BOOKS_DETAIL_CACHE_TTL = 60 * 10  # Cache book details for 10 minutes
AUTHOR_CACHE_TTL = 60 * 60  # Cache author details for 1 hour
TAG_CACHE_TTL = 60 * 600  # Cache tag details for 10 hours
USERBOOKS_CACHE_TTL = 60 * 60  # Cache userbooks list for 1 hour
USERBOOKS_DETAIL_CACHE_TTL = 60 * 120  # Cache userbook details
REVIEWS_CACHE_TTL = 60 * 5  # 5 minutes
REVIEWS_DETAIL_CACHE_TTL = 60 * 60  # 1 hour

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
    ('de', 'German'),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'ru'},
        {'code': 'en'},
        {'code': 'de'},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    },
}

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])  # pyright: ignore[reportArgumentType]
CORS_ALLOW_CREDENTIALS = True

# Frontend
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')  # pyright: ignore[reportArgumentType]

# Email
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')  # pyright: ignore[reportArgumentType]
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')  # pyright: ignore[reportArgumentType]
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')  # pyright: ignore[reportArgumentType]
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')  # pyright: ignore[reportArgumentType]
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')  # pyright: ignore[reportArgumentType]

# Celery
CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-reset-tokens': {
        'task': 'apps.users.tasks.cleanup_expired_reset_tokens',
        'schedule': timedelta(hours=6),
    },
}

SECURE_CONTENT_TYPE_NOSNIFF = True

# Throttle rates
ANON_THROTTLE_RATE = env('ANON_THROTTLE_RATE', default='60/min')  # pyright: ignore[reportArgumentType]
USER_THROTTLE_RATE = env('USER_THROTTLE_RATE', default='300/min')  # pyright: ignore[reportArgumentType]
REGISTER_THROTTLE_RATE = env('REGISTER_THROTTLE_RATE', default='10/hour')  # pyright: ignore[reportArgumentType]
LOGIN_THROTTLE_RATE = env('LOGIN_THROTTLE_RATE', default='5/min')  # pyright: ignore[reportArgumentType]
PASSWORD_RESET_THROTTLE_RATE = env('PASSWORD_RESET_THROTTLE_RATE', default='5/hour')  # pyright: ignore[reportArgumentType]

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.users.authentification.TokenVersionJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': ANON_THROTTLE_RATE,
        'user': USER_THROTTLE_RATE,
        'register': REGISTER_THROTTLE_RATE,
        'login': LOGIN_THROTTLE_RATE,
        'password_reset': PASSWORD_RESET_THROTTLE_RATE,
    },
    'EXCEPTION_HANDLER': 'apps.common.exceptions.custom_exception_handler',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# logging
LOGGING = {
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'app.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
        },
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# drf spectacular

SPECTACULAR_SETTINGS = {
    'TITLE': 'Book & Comic Reading Progress Tracker API',
    'DESCRIPTION': 'API for tracking reading progress of books and comics.',
    'VERSION': '1.0.0',
    # Split request/response schemas so that read-only fields (id, created_at,
    # updated_at …) are excluded from POST/PUT/PATCH request bodies in Swagger.
    'COMPONENT_SPLIT_REQUEST': True,
}

# django admin

ADMIN_SITE_HEADER = "Book Tracker Admin"
ADMIN_SITE_TITLE = "Book Tracker Admin"
ADMIN_INDEX_TITLE = "Book Tracker Administration"
ALLOWED_ADMIN_IPS = env.list('ALLOWED_ADMIN_IPS', default=['127.0.0.1'])  # pyright: ignore[reportArgumentType]
DJANGO_ADMIN_PATH = env('DJANGO_ADMIN_PATH', default='admin/')  # pyright: ignore[reportArgumentType]

# static
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
