# Generated by Django 6.0.2 on 2026-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
