# Generated by Django 6.0.2 on 2026-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_reviews_rev_user_id_a65d48_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=50000),
        ),
    ]
